### PR TITLE
Install all hooks

### PR DESCRIPTION
**Pull request by 59naga**
Citing the official, Has been changed to install the following hook.
> [Git - githooks Documentation](http://git-scm.com/docs/githooks)
* __applypatch-msg__
* pre-applypatch
* __post-applypatch__
* pre-commit
* __prepare-commit-msg__
* __commit-msg__
* __post-commit__
* pre-rebase
* __post-checkout__
* post-merge
* pre-push
* __pre-receive__
* update
* __post-receive__
* post-update
* __pre-auto-gc__
* post-rewrite

### CODE REVIEW

**Comment by gtramontina** [comment]
Very nice! Thanks for your contribution! :thumbsup: :beers: 
I thought of doing it right from the beginning, but then I realized that some of those hooks take parameters (like `prepare-commit-msg` for example). I'll merge your PR and update the `README` so it mentions that hooks that take parameters are not receiving any at the moment...

Once again, thanks!

**Comment by 59naga** [comment]
This project is very cool. I want to support you.

**Comment by gtramontina** [comment]
Published to npm: `+ ghooks@0.3.2` :beers:

**Comment by 59naga** [comment]
thanks!

**Pull request merged**
