### PR TITLE
Some minor updates to the install script

### PR DESCRIPTION
**Pull request by networkerror**
I updated install:

- You can run it from any directory and it will successfully find the hook.template file.  (yay)
- It won't overwrite backup hook files if you run npm install more than once.

### CODE REVIEW

**Comment by noamokman** [comment]
Hi there!
I think we should use [find-parent-dir](https://github.com/thlorenz/find-parent-dir).
This package is commonly used to find the project root dir.
The exmaple on thier readme is:
```js
// assuming this is called from a file in a subdirectory of /myprojects/foo which contains .git directory
var findParentDir = require('find-parent-dir');

findParentDir(__dirname, '.git', function (err, dir) {
  // has err if some file access error occurred
  console.log(dir); // => /myprojects/foo/

  // if parent dir wasn't found, dir is null
})
```

@kentcdodds What do you think?

**Comment by kentcdodds** [comment]
Sounds good to me. Either way, this PR needs to be updated so it merges nicely.

**Comment by noamokman** [comment]
@kentcdodds on second thoughts, using `find-parent-dir` also kinda closes #21 and #3.

**Comment by kentcdodds** [comment]
crickets here, closing.

**Pull request closed without merging**
