### PR TITLE
Test fixed for: Use eslint and @kentcdodds' presets

### PR DESCRIPTION
**Pull request by ta2edchimp**
Fixes the broken test of #43 
See [original PR for description](https://github.com/gtramontina/ghooks/pull/43#issuecomment-201930440)

### CODE REVIEW

**Comment by kentcdodds** [comment]
LGTM. I think there's a problem with our Travis setup. We can work that out later.

**Comment by ta2edchimp** [comment]
In the last commit I reverted the `coverage` script back to the original one, but updated `istanbul` to version `1.0.0-alpha`.
This fixes the broken tests/coverage report on Node ≤ `0.12`.

I have no clue why it is so, but somehow the automatic integration with Travis CI and it reporting back the result here, broke (this could be due to me, setting up travis for my fork).
We could trigger it, after I removed it from my travis account — but for the time being, [it's fixed for `0.10` and `0.12`](https://travis-ci.org/ta2edchimp/ghooks/builds/118790877)...

**Comment by gtramontina** [comment]
This is great! Thanks a lot for taking over the branch and continuing the work, @ta2edchimp… :beers:

Any thoughts on how to get this merged? Should we just merge this branch straight away, or cherry-pick @ta2edchimp's commits into #43 and reword/squash some commits (given that 83ea9f9's commit message is no longer true)…

:thought_balloon:

**Comment by ta2edchimp** [comment]
I could make a PR to your `gtramontina/eslint` branch and we could than simply squash the commits in question, if that helps.

**Comment by kentcdodds** [comment]
I'm indifferent. However you folks want to do this :-)

**Comment by ta2edchimp** [comment]
I just made #53 so @gtramontina could go whichever way he wants to :grin:

**Comment by ta2edchimp** [comment]
superceded by #53

**Pull request closed without merging**
