### PR TITLE
docs(install): instruct to use npm explore in non-git repo warning

### LINKED ISSUE #104: Incorrect follow-up command when installed in non-git project
If ghooks is installed in a project that isn't a git repo, it helpfully prints out a warning (https://github.com/gtramontina/ghooks/blob/master/lib/install.js#L68).  However, this line is incorrect:
> Run "git init" and then "npm run ghooks install"

`npm run` hasn't been able to run dependencies' scripts since npm@2 (https://github.com/npm/npm/issues/9186). The workaround is to instead run `npm explore ghooks -- npm run install`.

### PR DESCRIPTION
**Pull request by Tapppi**
Fixes #104

### CODE REVIEW

**Comment by Tapppi** [comment]
Dont know if the docs type makes sense, or if it should be style/refactor.. Sorry I'm still fairly new to the angular format :disappointed: Also forgot the fixes footer from the commit.. Ah crap.

**Comment by ta2edchimp** [comment]
You could use `git commit --amend` to alter you last commits' message (I'd say `style` or sth. but am unsure as well considering this particular example) and force push to your remote branch. This PR would update automatically afterwards.

While thinking about it, **personally** I'd say even make it a `fix` (this would trigger a new semantic release after merging).

**Comment by kentcdodds** [comment]
This looks fine to me. I probably wouldn't call this a `docs` change but a `fix`. But lucky for both of us, GitHub now allows me to update your commit message for you!

I'll go ahead and merge this and update the message for you :-) Thanks for the contribution!

**Comment by Tapppi** [comment]
Thank you for the quick response!1 :+1:

**Pull request merged**
