### PR TITLE
feat(hook): Support setups with CWD below Git project root

### PR DESCRIPTION
**Pull request by ta2edchimp**
Refers to issue #78 (`ghooks not found!`).

### CODE REVIEW

**Comment by kentcdodds** [comment]
Code looks good. Let's fix up the tests (and maybe write one out two more)

**Comment by ta2edchimp** [comment]
After a bit of fiddling around with those two failing tests, I think I can come up with a solution:
https://github.com/Prophet32j/ghooks/pull/1/commits/a599dffd06a4ed6e8aa900992745d716458d0f5f

It should still be checked

* [ ] if the setup of the `ghooks` project's own hooks still works @ install,
* [ ] if it does not break in a default project setup (`node_modules` folder directly below project root).

So, I agree that there's a need for one or two new tests to be written.

@Prophet32j can merge my alterations into his branch to update this PR.

**Comment by Prophet32j** [comment]
PR is merged. I will try and throw together a couple tests on the new code.

We should note that globally installed `ghooks` will fail now since we aren't checking for doing `require('ghooks')` anymore.

**Comment by ta2edchimp** [comment]
Well, some people are used to install such modules globally, so I think we should rather try to detect this and handle it accordingly, than just ditch that case. I'm pretty sure I had found an example of how to detect it, but I cannot come up with what or where that was from the back of my head right now ...

**Comment by kentcdodds** [comment]
I can't think of a case where a global install would even make sense... how would the hooks get installed without a local install?

**Comment by Prophet32j** [comment]
Checked `npm install` on my fork. The hooks are throwing errors because I assumed that ghooks was always being installed from outside its own repository. Doing `npm install` on itself creates a bad path to `node_modules`. Output from the install:

`var nodeModulesPath = '/Users/joshuahardy/projects/github';`

expected:

`var nodeModulesPath = '/Users/joshuahardy/projects/github/ghooks/node_modules';`

We could modify `exports.content` to check if `node_modules` exists within the CWD. If it does, we can assume an external project is installing ghooks, else we can assume that ghooks is installing itself.
________________________

Checked a default project setup with no nested npm projects. This worked as expected.

    "config": {
        "ghooks": {
          "pre-commit": "echo \"HELLLO WORLD\""
        }
    }

I received a good `HELLO WORLD` on the console. Snippet from the installed pre-commit file:

`var nodeModulesPath = '/Users/joshuahardy/projects/github/test/node_modules';`

Both default and nested project structures work correctly.
Default:

    - root
      + .git
      + package.json
      + node_modules

Nested:

    - root
      + .git
      + npm_project_root
        - package.json
        - node_modules

**Comment by Prophet32j** [comment]
@kentcdodds

    function getGitRoot() {
      const gitRoot = findup.sync(process.cwd(), '.git')
      ...

if it doesn't find it, it will throw an error and return fall to `findGitRoot()`

I don't see why anyone would install ghooks globally. It doesn't make a whole lot of sense since you would want to ensure you install hooks for each project.

**Comment by ta2edchimp** [comment]
>I can't think of a case where a global install would even make sense... how would the hooks get installed without a local install?

Yes, of course. I was confused ...

**Comment by ta2edchimp** [comment]
To continue here, what is it that should be done to complete this PR?

* fix rendered `nodeModulesPath` on install of ghooks' own repo
* cover all possible cases with appropriate tests:
  * `cwd` === project root (default, covered already)
  * `cwd` below project root (to be implemented)
* extend `README` to mention to not install `ghooks` globally

Did I miss anything?

@Prophet32j are you still working on this or waiting for response regarding the case of setting up the hooks for ghooks' own repo?

**Comment by Prophet32j** [comment]
Hi, sorry. I have been gone for the national guard for the past 2 weeks. I tried finishing while I was on the bus, but I couldn't find the time.

**Comment by ta2edchimp** [comment]
Would it be ok for you if we'd continue from this point on?

**Comment by Prophet32j** [comment]
Yes that would be fine.

**Comment by tw0517tw** [comment]
https://github.com/gtramontina/ghooks/pull/108/files#diff-b3b53682a18f203ac8d29b0e277cad26L16
above line won't work on Windows machines

**Comment by ta2edchimp** [comment]
@tw0517tw you're right. We should have split by `path.sep`. I totally forgot to replace that when following up on this PR with #112

**Comment by KristianSelnas** [comment]
`.replace('{{node_modules_path}}', path.join(process.cwd(), '..'))` in hook.template.js doesn't seem to work on Windows either. When used as a string, the path separators (backslashes) effectively become escape characters.

**Comment by ta2edchimp** [comment]
#114 should take care of both issues now.

**Pull request closed without merging**
