### PR TITLE
Follow up to #108: Support setups with CWD below Git project root

### PR DESCRIPTION
**Pull request by ta2edchimp**
Supersedes #108

### CODE REVIEW

**Comment by ta2edchimp** [comment]
* [x] fix rendered `nodeModulesPath` on install of ghooks' own repo  
👉 [_tries to resolve `ghooks` directly, first (by `git worktree` or `nodeModulesPath` afterwards)_](https://github.com/gtramontina/ghooks/pull/112/files#diff-07a81d82ccc03cfdbbdb8416bdbd89f8R13)
* [x] cover all possible cases with appropriate tests:
  * [x] [`cwd` === project root (default, covered already)](https://github.com/gtramontina/ghooks/pull/112/files#diff-57c00b1d194c78623f9c6b7a8f326d3eR12)
  * [x] [`cwd` below project root (to be implemented)](https://github.com/gtramontina/ghooks/pull/112/files#diff-57c00b1d194c78623f9c6b7a8f326d3eR29)
* [x] [extend `README` to mention to not install `ghooks` globally](https://github.com/gtramontina/ghooks/pull/112/files#diff-04c6e90faac2675aa89e2176d2eec7d8R25)

I think we got everything covered, or did I miss anything?

**Comment by kentcdodds** [comment]
LGTM!

**Comment by Prophet32j** [comment]
Thanks for finishing this for me. I'm only now getting back to work.

**Comment by gtramontina** [comment]
It does look good to me! 👍
Thanks for all the effort in going to the root cause and addressing the issue!

Should we amend the commit messages/squash some of them before merging?

**Comment by kentcdodds** [comment]
We can do that in the GitHub ui now

**Pull request merged**
