### PR TITLE
fix(hook): handle node module path os agnostically

### PR DESCRIPTION
**Pull request by ta2edchimp**
[Former `hook` name determination was a simple regex using *nix style path separator `/`](https://github.com/gtramontina/ghooks/blob/master/lib/runner.js#L15-L17), using `path.basename`, the required last part gets returned, independent of an os specific path separator.

### CODE REVIEW

**Comment by ta2edchimp** [comment]
Should we investigate means to also automatically test on Windows environments? ([AppVeyor](https://www.appveyor.com/docs/lang/nodejs-iojs) comes to my mind, but atm I have no clue how we could get the semantic releases to also depend on successful builds on another platform

**Comment by kentcdodds** [comment]
Yes, this is needed.

**Comment by kentcdodds** [comment]
> Should we investigate means to also automatically test on Windows environments?

Yeah, probably should

> (AppVeyor comes to my mind, but atm I have no clue how we could get the semantic releases to also depend on successful builds on another service ...)

We could create a `release` branch and merge `master` into that branch when we're ready to do the release. Requires an extra step, but that would allow us to make sure that things look good.

Or we could just keep things as-is and rely on the pull request status checks. If the PR passes AppVeyor, then we'll assume that it'll pass when it merges into master. I think that'd be sufficient.

I've tried AppVeyor once and failed to get it working. But I think it'd be great to have it working on this project.

**Comment by ta2edchimp** [comment]
>Or we could just keep things as-is and rely on the pull request status checks. If the PR passes AppVeyor, then we'll assume that it'll pass when it merges into master. I think that'd be sufficient.

Sounds like a plan that should suffice.

**Comment by gtramontina** [comment]
I agree with this second approach as it seems simpler to get working. If I remember correctly, we can set github up so it doesn't allow for merging PRs if some checks fail…

BTW, thanks for addressing this issue right away!!

**Pull request merged**
